package skill

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The plugin ships the same skill the binary embeds, and ships it as a second
// copy on disk because a plugin is a directory and go:embed cannot reach
// outside its own package.
//
// Two copies of anything drift. This repository has been bitten twice: the
// installer carried its own ASCII mark and was a respacing behind for two
// releases, and the skill described a --name flag that promote does not take.
// The copy is generated by `make plugin`; this fails when somebody edits one
// and not the other.
func TestThePluginShipsTheSkillTheBinaryEmbeds(t *testing.T) {
	copied, err := os.ReadFile(filepath.Join("..", "..",
		"plugins", "braids", "skills", "braids", "SKILL.md"))
	if err != nil {
		t.Fatalf("read the plugin's skill: %v", err)
	}
	embedded, err := os.ReadFile("SKILL.md")
	if err != nil {
		t.Fatal(err)
	}
	if normalise(string(copied)) != normalise(string(embedded)) {
		t.Error("the plugin's skill and the embedded one have drifted.\n" +
			"Run: make plugin")
	}
}

// A marketplace that points at a plugin directory which is not there installs
// nothing, and says so only to whoever tried.
func TestTheMarketplacePointsAtSomethingReal(t *testing.T) {
	root := filepath.Join("..", "..")
	body, err := os.ReadFile(filepath.Join(root, ".claude-plugin", "marketplace.json"))
	if err != nil {
		t.Fatalf("read the marketplace: %v", err)
	}
	var market struct {
		Name    string `json:"name"`
		Plugins []struct {
			Name   string `json:"name"`
			Source string `json:"source"`
		} `json:"plugins"`
	}
	if err := json.Unmarshal(body, &market); err != nil {
		t.Fatalf("the marketplace is not valid JSON: %v", err)
	}
	if market.Name == "" || len(market.Plugins) == 0 {
		t.Fatal("the marketplace names no plugins")
	}
	for _, p := range market.Plugins {
		dir := filepath.Join(root, filepath.FromSlash(strings.TrimPrefix(p.Source, "./")))
		manifest := filepath.Join(dir, ".claude-plugin", "plugin.json")
		if _, err := os.Stat(manifest); err != nil {
			t.Errorf("plugin %q points at %s, which has no manifest: %v", p.Name, p.Source, err)
		}
		// Its hooks must run braids from PATH. A plugin cannot know where a
		// binary it did not install ended up, and an absolute path baked in
		// here would be one machine's truth shipped to everybody.
		hooks, err := os.ReadFile(filepath.Join(dir, "hooks", "hooks.json"))
		if err != nil {
			continue
		}
		if strings.Contains(string(hooks), "/braids") {
			t.Errorf("plugin %q hooks name an absolute path to braids", p.Name)
		}
		if !strings.Contains(string(hooks), `"braids hook"`) {
			t.Errorf("plugin %q hooks do not run `braids hook`", p.Name)
		}
	}
}
