package skill

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The plugin ships the same skill the binary embeds, and ships it as a second
// copy on disk because a plugin is a directory and go:embed cannot reach
// outside its own package.
//
// Two copies of anything drift. This repository has been bitten twice: the
// installer carried its own ASCII mark and was a respacing behind for two
// releases, and the skill described a --name flag that promote does not take.
// The copy is generated by `make plugin`; this fails when somebody edits one
// and not the other.
func TestThePluginShipsTheSkillTheBinaryEmbeds(t *testing.T) {
	copied, err := os.ReadFile(filepath.Join("..", "..",
		"plugins", "braids", "skills", "braids", "SKILL.md"))
	if err != nil {
		t.Fatalf("read the plugin's skill: %v", err)
	}
	embedded, err := os.ReadFile("SKILL.md")
	if err != nil {
		t.Fatal(err)
	}
	if normalise(string(copied)) != normalise(string(embedded)) {
		t.Error("the plugin's skill and the embedded one have drifted.\n" +
			"Run: make plugin")
	}
}

// A marketplace that points at a plugin directory which is not there installs
// nothing, and says so only to whoever tried.
func TestTheMarketplacePointsAtSomethingReal(t *testing.T) {
	root := filepath.Join("..", "..")
	body, err := os.ReadFile(filepath.Join(root, ".claude-plugin", "marketplace.json"))
	if err != nil {
		t.Fatalf("read the marketplace: %v", err)
	}
	var market struct {
		Name    string `json:"name"`
		Plugins []struct {
			Name   string `json:"name"`
			Source string `json:"source"`
		} `json:"plugins"`
	}
	if err := json.Unmarshal(body, &market); err != nil {
		t.Fatalf("the marketplace is not valid JSON: %v", err)
	}
	if market.Name == "" || len(market.Plugins) == 0 {
		t.Fatal("the marketplace names no plugins")
	}
	for _, p := range market.Plugins {
		dir := filepath.Join(root, filepath.FromSlash(strings.TrimPrefix(p.Source, "./")))
		manifest := filepath.Join(dir, ".claude-plugin", "plugin.json")
		if _, err := os.Stat(manifest); err != nil {
			t.Errorf("plugin %q points at %s, which has no manifest: %v", p.Name, p.Source, err)
		}
		// Its hooks must run braids from PATH. A plugin cannot know where a
		// binary it did not install ended up, and an absolute path baked in
		// here would be one machine's truth shipped to everybody.
		hooks, err := os.ReadFile(filepath.Join(dir, "hooks", "hooks.json"))
		if err != nil {
			continue
		}
		if strings.Contains(string(hooks), "/braids") {
			t.Errorf("plugin %q hooks name an absolute path to braids", p.Name)
		}
		if !strings.Contains(string(hooks), `"braids hook"`) {
			t.Errorf("plugin %q hooks do not run `braids hook`", p.Name)
		}
	}
}

// Installing braids twice is easy and invisible. The plugin brings the skill,
// `braids skill --install` writes another, and Claude loads the same
// instructions under two names while nothing says so, because from Claude
// Code's side they are two skills that happen to agree.
//
// Found by installing the plugin from the marketplace onto a machine that
// already had the skill, and asking a session what it had.
func TestAPluginCopyIsFound(t *testing.T) {
	plugins := t.TempDir()
	// The cache nests a marketplace, a plugin and a revision before the
	// skills directory, so the search cannot assume a depth.
	deep := filepath.Join(plugins, "cache", "braids", "braids", "17587872eef9", "skills", "braids")
	if err := os.MkdirAll(deep, 0o755); err != nil {
		t.Fatal(err)
	}
	if got := PluginPath(plugins); got != "" {
		t.Errorf("found %q with no skill file there", got)
	}
	want := filepath.Join(deep, "SKILL.md")
	if err := os.WriteFile(want, []byte("---\nname: braids\n---\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if got := PluginPath(plugins); got != want {
		t.Errorf("PluginPath = %q, want %q", got, want)
	}
}

// A directory with no plugins at all, and one that does not exist, are both
// simply no plugin rather than an error: this is asked on every `braids
// skill` and must never be the thing that fails.
func TestNoPluginCopyIsNotAnError(t *testing.T) {
	if got := PluginPath(t.TempDir()); got != "" {
		t.Errorf("an empty plugins directory gave %q", got)
	}
	if got := PluginPath(filepath.Join(t.TempDir(), "nothing", "here")); got != "" {
		t.Errorf("a missing plugins directory gave %q", got)
	}
}
